name: wifiber
description: "Aplikasi portal billing Wifi milik PT Jawara Lintas Nusantara"
publish_to: "none"
version: 1.1.6+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.2.1
  icons_launcher: ^3.0.1
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  skeletonizer: ^2.1.0+1
  phosphor_flutter: ^2.1.0
  remixicon: ^1.4.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.18.0
  cached_network_image: ^3.3.1
  sqflite: ^2.3.0
  path: ^1.8.0
  crypto: ^3.0.3
  build_runner: ^2.3.3
  build: ^2.4.0
  url_launcher: ^6.3.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  file_picker: 10.2.0
  maps_launcher: ^3.0.0+1
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0

  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/summary-image.png
    - assets/logo/
    - assets/logo/
    - assets/onboardings/
